apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.config.DJANGO_SETTINGS_MODULE | quote }}
  SEEDING_MAX_PAGES: {{ .Values.config.SEEDING_MAX_PAGES | quote }}
  ALLOWED_HOSTS: {{ .Values.config.ALLOWED_HOSTS | quote }}
  FRONTEND_URL: {{ .Values.config.FRONTEND_URL | quote }}
  REDIS_LOCATION: {{ .Values.config.REDIS_LOCATION | quote }}
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
