datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: true
    basicAuthUser: grafana
      
    secureJsonData:
      basicAuthPassword: grafana
      
    jsonData:
      tlsSkipVerify: true

    isDefault: true
    editable: true