apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-postgres-pv-0
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/k3s/pgdata/db-0
    server: main
    
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pvc
# spec:
#   resources:
#     requests:
#       storage: 250Mi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: slow
#   volumeName: nfs-postgres-pv