apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  DJANGO_SETTINGS_MODULE: gamehub.settings.prod
  SEEDING_MAX_PAGES: "5"
  ALLOWED_HOSTS: .gamehub.cum,gamehub.cum
  FRONTEND_URL: http://gamehub.cum
  REDIS_LOCATION: redis://redis-bitnami-master:6379/1
  DB_HOST: postgres-cloudpirates
  DB_PORT: "5432"
