apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SECRET_KEY: XXXX                 # Django secret key 
  RAWG_API_KEY: XXXX               # rawg api key 
  DB_NAME: DATABASE_NAME           # "gamehub_db"
  DB_USER: POSTGRES_USER           # postgres default admin user is "postgres"
  DB_PASSWORD: POSTGRES_PASSWORD   # postgres default admin password is "postgres"
